#!/usr/bin/perl

while (<>) {
	($id, $name, $id2, $date, $time, @fields) = split(/,/);

	$drive = 0;
	for ($i = 0; $i < 12; $i++) {
		$drive += $fields[$i];
	}
	$walk = $fields[12] + $fields[13] + $fields[14] + $fields[15];
	$bike = $fields[16] + $fields[17] + $fields[18] + $fields[19];

	if ($time =~ /^(\d+):(\d+)\s*-+\s*(\d+):(\d+)$/) {
			($h1, $m1, $h2, $m2) = ($1, $2, $3, $4);
		$dur = ($h2 * 60 + $m2) - ($h1 * 60 + $m1);

		if ($dur == 60 || $dur == 630) {
			if ($walk >= $walk{$name}{$dur}) {
				$walk{$name}{$dur} = $walk;
			}

			if ($bike >= $bike{$name}{$dur}) {
				$bike{$name}{$dur} = $walk;
			}

			if ($drive >= $drive{$name}{$dur}) {
				$drive{$name}{$dur} = $walk;
			}
		}
	}
}

for $name (keys(%walk)) {
	print "$drive{$name}{630} $drive{$name}{60} ";
	print "$walk{$name}{630} $walk{$name}{60} ";
	print "$bike{$name}{630} $bike{$name}{60} ";

	print "# $name\n";
}
